### PR TITLE
[1434] Support viewing school nav tabs

### PR DESCRIPTION
**Pull request by asmega**
### Context

- https://trello.com/c/XaACO5uV/1434-support-improvement-recent-history-for-each-school

### Changes proposed in this pull request

- Add tabs to support viewing a school
- Add new `Timeline` tab/concept
- Timeline is chronological timeline (maybe it should be reverse chronological order?) of certain changesets at the moment. This can be expanded out to other changes or refined to show fewer changes useful for support
- `/history` has been changes so items in the same changeset share the same date with one table cell with rowspan set

### Screenshots

image

image

image

image

### Guidance to review

- n/a

### CODE REVIEW

**Comment by ralph-hawkins** [comment]
This is great @asmega, a couple of minor things:

- can we add an h2 to each tab (with the name of that tab) – it will help with screen readers and if js isn’t working
- I think using the tag style is unnecessary for what's changed in the timeline, the layout is clear enough – can we remove them, please?

**Comment by asmega** [comment]
> This is great @asmega, a few minor things:
> 
> * can we add an h2 to each tab (with the name of that tab) – it will help with screen readers and if js isn’t working
> * I think using the tag style is unnecessary for what's changed in the timeline, the layout is clear enough – can we remove them, please?
> * can you increase the width to the time column in the notifications tab? it's a little hard to read

@ralph-hawkins Thanks for the feedback. I've just incorporated all your suggestions and updated the screenshots.

**Comment by jamesrose** [comment]
Hey @asmega - this looks awesome. Do you think it's too much of a faff to try and localize the values of the timeline? That data values are much more familiar with us than other support people. Not a huge deal, either way.

**Review by aldavidson — APPROVED** [review]
This tidies up the interface a lot, good stuff :+1:

**Comment by asmega** [comment]
> Hey @asmega - this looks awesome. Do you think it's too much of a faff to try and localize the values of the timeline? That data values are much more familiar with us than other support people. Not a huge deal, either way.

I've added i18n to the field column, i think the data values are acceptable for now. Screenshot has been updated. I also removed a few field from the timeline as they may be noise. I think we need what this like with all the data on prod and make changes accordingly

**Pull request merged**
