### PR TITLE
Remove Rails UJS since we don't use it

### PR DESCRIPTION
**Pull request by benilovj**
### Context

We don't need/want to use Rails UJS, and its magic has bitten me once already during development.

### Changes proposed in this pull request

- Remove Rails UJS.
- Change the sign out link to use GET instead of DELETE.

### CODE REVIEW

**Comment by tijmenb** [comment]
I suspect this might break the logout link, I think `method` only works with UJS: https://github.com/DFE-Digital/get-help-with-tech/blob/3ab357fdbac8be652f00751d5c9210c070cbaaae/app/views/layouts/_nav.html.erb#L16

**Comment by benilovj** [comment]
> I suspect this might break the logout link, I think `method` only works with UJS:
> 
> https://github.com/DFE-Digital/get-help-with-tech/blob/3ab357fdbac8be652f00751d5c9210c070cbaaae/app/views/layouts/_nav.html.erb#L16

Ah good catch - thanks.

**Comment by fofr** [comment]
Can confirm that with JS disabled our current "Sign out" link doesn't work.

**Comment by benilovj** [comment]
> Can confirm that with JS disabled our current "Sign out" link doesn't work.

I've added a2e05ff which should fix the issue – @fofr you mind giving it another go using this branch?

**Comment by fofr** [comment]
@benilovj Sign out works with JS disabled on this branch.

**Comment by aldavidson** [comment]
I'm in favour of not relying on Javascript, but I'm not sure about the sign out link becoming a regular GET - it will work, but it breaks the RESTfulness model and introduces some potential issues (for instance, it's then possible for the users' browser to follow the link pre-emptively and sign the user out without them knowing).

I'm going to try an alternative, will add it as a suggested change if it works - please hold off merging this for the moment

**Comment by benilovj** [comment]
> I'm going to try an alternative, will add it as a suggested change if it works - please hold off merging this for the moment

Sure. FWIW, I looked to Apply for Teacher Training for inspiration...

**Comment by aldavidson** [comment]
I've put my alternative up as a separate PR - #137 . It solves the problems of signout-as-GET, at the expense of a few lines of CSS.

**Comment by benilovj** [comment]
Closing since #137 has been merged instead.

**Pull request closed without merging**
