### PR TITLE
Show privacy notice to responsible body users

### PR DESCRIPTION
**Pull request by benilovj**
Show the privacy notice to first-time RB users.

### CODE REVIEW

**Review by aldavidson — APPROVED** [review]
Looks OK to me - if I'm reading this right, it's still possible for an RB user who is shown the notice to get to the other pages without clicking Continue, but that may be a design choice (they'll get shown it again next time they log in)

**Comment by benilovj** [comment]
> Looks OK to me - if I'm reading this right, it's still possible for an RB user who is shown the notice to get to the other pages without clicking Continue, but that may be a design choice (they'll get shown it again next time they log in)

yep i think that's ok for now

**Comment by fofr** [comment]
Assume it's ok for RB users who are only in the connectivity pilot to see this too?

**Comment by benilovj** [comment]
> Assume it's ok for RB users who are only in the connectivity pilot to see this too?

I think that's ok.

**Pull request merged**
