### PR TITLE
Enable moving backwards in wizard

### PR DESCRIPTION
**Pull request by tonyheadford**
### Context
[Trello card](https://trello.com/c/oB609ypc/629-allow-users-to-use-the-browsers-back-button-in-the-school-wizard)

### Changes proposed in this pull request
Pass wizard step to update method to enable back button to work as expected
Invite additional user only available to "first" school user
Chromebooks page only shown to "first" school user

### Guidance to review
Will need a good check of the flows through the wizard and using the back button to repeat steps.  Check that the user journey still makes sense.

### CODE REVIEW

**Comment by fofr** [comment]
> Chromebooks page only shown to "first" school user
Why did we decide this?

**Comment by tonyheadford** [comment]
> > Chromebooks page only shown to "first" school user
> 
> Why did we decide this?

I was trying to keep the movement through the wizard consistent, happy to change it if you want.  My thinking - the `:will_need_chromebooks` attribute has 3 states `yes`, `no` and `nil` (used for 'I don't know'). The first user has to make a choice.  That user can now go backwards and change that choice while in the wizard - previously the page was only shown if `:will_need_chromebooks` was `nil`.  However, now that we can go backwards, If we only show the page when that value is `nil` it means the user cannot get to it again while in the wizard - or rather, if they go backwards to the step before it and then try to step into it again, it would be skipped which makes the journey inconsistent?

**Comment by fofr** [comment]
We need both:
- back/forward must work for users who see this page
- we need to show it to subsequent users if the value isn't set

**Comment by fofr** [comment]
When a user signs in, can we decide what pages they see in the wizard? Rather than at the point of navigation.

**Comment by tonyheadford** [comment]
I kind of do that already for the first user but I'm thinking if we extend
that to the chromebooks and store that in the wizard we can control
access/visibility forwards and backwards to that page

**Review by benilovj — APPROVED** [review]
Code changes look good, deferring to @fofr on the correct behaviour...

**Comment by tonyheadford** [comment]
@fofr updated so now it records the decision on whether the user should be able to see the chromebooks page based on whether the questions has already been answered or not. Once that use has been given access to the chromebooks page, they can navigate forwards and backwards through the wizard and still see the page regardless of whether they have answered the question or not.

**Comment by fofr** [comment]
Back and forward seem to work ok now.
If you use back or forward and then refresh the journey behaves strangely again (going to the latest not-seen page).

I think we need to rethink this because we shouldn't be breaking browser features like this, but for now we need to ship.

**Review by fofr — APPROVED** [review]

**Pull request merged**
