### PR TITLE
Add CSV export for `Asset`s

### PR DESCRIPTION
**Pull request by nigel-lowry**
### Context

https://trello.com/c/gKdKsd5W

### Changes proposed in this pull request

Original CSV sanitiser wasn't actually making CSVs safe (if they're exported into Microsoft Excel) so rewrote that.

### CODE REVIEW

**Comment by nigel-lowry** [comment]
[Admin Bios - Export asset information to file](https://trello.com/c/gKdKsd5W/2308-admin-bios-export-asset-information-to-file)

**Comment by nigel-lowry** [comment]
[Amendment to Admin-BIOS signed in copy](https://trello.com/c/6gpmNl9o/2390-amendment-to-admin-bios-signed-in-copy)

**Comment by nigel-lowry** [comment]
[What is a Hardware hash explainer](https://trello.com/c/fAnjrWx3/2392-what-is-a-hardware-hash-explainer)

**Review by kenfodder — APPROVED** [review]

**Review by markhallen — APPROVED** [review]
Nice work!

**Review by markhallen — APPROVED** [review]

**Pull request merged**
