### PR TITLE
2350 and 2418 4G routers reinstatement

### PR DESCRIPTION
**Pull request by nigel-lowry**
### Context

Covers both school and RB 4G routers

https://trello.com/c/MBXClJOI
https://trello.com/c/AGE8utGk

### Changes proposed in this pull request

Removed defunct "closed banner". This contained some information about previous purchases but will be replaced by something different in a future ticket (it's better to write that properly as a ViewComponent and unit test it rather than do it in a UI test as it was here)

### CODE REVIEW

**Comment by nigel-lowry** [comment]
[School: Request 4G Routers](https://trello.com/c/MBXClJOI/2350-school-request-4g-routers)

**Comment by nigel-lowry** [comment]
[RB: Request 4G routers](https://trello.com/c/AGE8utGk/2418-rb-request-4g-routers)

**Comment by nigel-lowry** [comment]
[School: Request 4G Routers](https://trello.com/c/MBXClJOI/2350-school-request-4g-routers)

**Review by kenfodder — DISMISSED** [review]
I think this needs rebasing, it's going back near 10 commits.

**Review by kenfodder — APPROVED** [review]

**Pull request merged**
